"""add new table

Revision ID: 0794d0599df8
Revises: de0432131a38
Create Date: 2026-09-07 09:58:07.976456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0794d0599df8'
down_revision: Union[str, Sequence[str], None] = 'de0432131a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('declarations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_financials_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('seller_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_financials_id'], ['business_financials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_financials_id')
    )
    op.create_index(op.f('ix_declarations_document_id'), 'declarations', ['document_id'], unique=True)
    op.create_index(op.f('ix_declarations_status'), 'declarations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_declarations_status'), table_name='declarations')
    op.drop_index(op.f('ix_declarations_document_id'), table_name='declarations')
    op.drop_table('declarations')
    # ### end Alembic commands ###
