"""add initialization time tracker to nda model

Revision ID: 0eadaaa48810
Revises: 02b891a72877
Create Date: 2026-09-25 15:25:53.399054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eadaaa48810'
down_revision: Union[str, Sequence[str], None] = '02b891a72877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ndas', sa.Column('signing_initialization_started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ndas', 'signing_initialization_started_at')
    # ### end Alembic commands ###
