"""add nda signature provider state

Revision ID: 2b2a51df6e60
Revises: 70e0c4d3ad49
Create Date: 2026-09-25 02:46:30.426657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b2a51df6e60'
down_revision: Union[str, Sequence[str], None] = '70e0c4d3ad49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ndas', sa.Column('signing_initialization_status', sa.String(length=30), nullable=False))
    op.create_index(op.f('ix_ndas_signing_initialization_status'), 'ndas', ['signing_initialization_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ndas_signing_initialization_status'), table_name='ndas')
    op.drop_column('ndas', 'signing_initialization_status')
    # ### end Alembic commands ###
