"""added about_me section to buyer profile

Revision ID: 4bd3b8a8029f
Revises: 6a3114993052
Create Date: 2026-09-21 07:00:29.251954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd3b8a8029f'
down_revision: Union[str, Sequence[str], None] = '6a3114993052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyer_profiles', sa.Column('about_me', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buyer_profiles', 'about_me')
    # ### end Alembic commands ###
