"""update database schema

Revision ID: 6a3114993052
Revises: 923821662f81
Create Date: 2026-09-18 09:59:14.465997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3114993052'
down_revision: Union[str, Sequence[str], None] = '923821662f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chat_generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_generations_conversation_id'), 'ai_chat_generations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_chat_generations_created_at'), 'ai_chat_generations', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_chat_generations_match_id'), 'ai_chat_generations', ['match_id'], unique=False)
    op.create_index(op.f('ix_ai_chat_generations_model'), 'ai_chat_generations', ['model'], unique=False)
    op.create_index('ix_ai_chat_generations_model_created', 'ai_chat_generations', ['model', 'created_at'], unique=False)
    op.create_index('ix_ai_chat_generations_prompt_created', 'ai_chat_generations', ['prompt_version', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_chat_generations_prompt_version'), 'ai_chat_generations', ['prompt_version'], unique=False)
    op.create_index(op.f('ix_ai_chat_generations_success'), 'ai_chat_generations', ['success'], unique=False)
    op.create_index('ix_ai_chat_generations_success_created', 'ai_chat_generations', ['success', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_chat_generations_user_id'), 'ai_chat_generations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_chat_generations_user_id'), table_name='ai_chat_generations')
    op.drop_index('ix_ai_chat_generations_success_created', table_name='ai_chat_generations')
    op.drop_index(op.f('ix_ai_chat_generations_success'), table_name='ai_chat_generations')
    op.drop_index(op.f('ix_ai_chat_generations_prompt_version'), table_name='ai_chat_generations')
    op.drop_index('ix_ai_chat_generations_prompt_created', table_name='ai_chat_generations')
    op.drop_index('ix_ai_chat_generations_model_created', table_name='ai_chat_generations')
    op.drop_index(op.f('ix_ai_chat_generations_model'), table_name='ai_chat_generations')
    op.drop_index(op.f('ix_ai_chat_generations_match_id'), table_name='ai_chat_generations')
    op.drop_index(op.f('ix_ai_chat_generations_created_at'), table_name='ai_chat_generations')
    op.drop_index(op.f('ix_ai_chat_generations_conversation_id'), table_name='ai_chat_generations')
    op.drop_table('ai_chat_generations')
    # ### end Alembic commands ###
