"""updated Nda table, made BuyerType column nullable and removed redundant verificationStatus column from buyerProfile and sellerProfile

Revision ID: 70e0c4d3ad49
Revises: 8a479c6efb4c
Create Date: 2026-09-25 01:37:29.051463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e0c4d3ad49'
down_revision: Union[str, Sequence[str], None] = '8a479c6efb4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buyer_profiles_verification_status'), table_name='buyer_profiles')
    op.drop_column('buyer_profiles', 'verification_status')
    op.add_column('ndas', sa.Column('signature_provider', sa.String(length=50), nullable=True))
    op.add_column('ndas', sa.Column('provider_document_id', sa.String(length=255), nullable=True))
    op.add_column('ndas', sa.Column('provider_template_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_ndas_provider_document_id'), 'ndas', ['provider_document_id'], unique=True)
    op.create_index(op.f('ix_ndas_signature_provider'), 'ndas', ['signature_provider'], unique=False)
    op.drop_index(op.f('ix_seller_profiles_verification_status'), table_name='seller_profiles')
    op.drop_column('seller_profiles', 'verification_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_profiles', sa.Column('verification_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_seller_profiles_verification_status'), 'seller_profiles', ['verification_status'], unique=False)
    op.drop_index(op.f('ix_ndas_signature_provider'), table_name='ndas')
    op.drop_index(op.f('ix_ndas_provider_document_id'), table_name='ndas')
    op.drop_column('ndas', 'provider_template_id')
    op.drop_column('ndas', 'provider_document_id')
    op.drop_column('ndas', 'signature_provider')
    op.add_column('buyer_profiles', sa.Column('verification_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_buyer_profiles_verification_status'), 'buyer_profiles', ['verification_status'], unique=False)
    # ### end Alembic commands ###
