"""added sub_industries and business_model

Revision ID: 8a479c6efb4c
Revises: 4bd3b8a8029f
Create Date: 2026-09-23 10:01:29.004622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a479c6efb4c'
down_revision: Union[str, Sequence[str], None] = '4bd3b8a8029f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('sub_industry', sa.String(length=150), nullable=False))
    op.add_column('businesses', sa.Column('business_model', sa.String(length=100), nullable=False))
    op.alter_column('businesses', 'business_type',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('businesses', 'industry',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_business_matching_industry'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_industry'), table_name='businesses')
    op.create_index('ix_business_matching_classification', 'businesses', ['status', 'industry', 'sub_industry'], unique=False)
    op.add_column('buyer_preferences', sa.Column('target_industry_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('buyer_preferences', sa.Column('target_business_models', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('buyer_preferences', sa.Column('target_business_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_buyer_preferences_target_industries_gin'), table_name='buyer_preferences', postgresql_using='gin')
    op.create_index('ix_buyer_preferences_target_business_models_gin', 'buyer_preferences', ['target_business_models'], unique=False, postgresql_using='gin')
    op.create_index('ix_buyer_preferences_target_business_types_gin', 'buyer_preferences', ['target_business_types'], unique=False, postgresql_using='gin')
    op.create_index('ix_buyer_preferences_target_industry_preferences_gin', 'buyer_preferences', ['target_industry_preferences'], unique=False, postgresql_using='gin')
    op.drop_column('buyer_preferences', 'target_industries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyer_preferences', sa.Column('target_industries', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index('ix_buyer_preferences_target_industry_preferences_gin', table_name='buyer_preferences', postgresql_using='gin')
    op.drop_index('ix_buyer_preferences_target_business_types_gin', table_name='buyer_preferences', postgresql_using='gin')
    op.drop_index('ix_buyer_preferences_target_business_models_gin', table_name='buyer_preferences', postgresql_using='gin')
    op.create_index(op.f('ix_buyer_preferences_target_industries_gin'), 'buyer_preferences', ['target_industries'], unique=False, postgresql_using='gin')
    op.drop_column('buyer_preferences', 'target_business_types')
    op.drop_column('buyer_preferences', 'target_business_models')
    op.drop_column('buyer_preferences', 'target_industry_preferences')
    op.drop_index('ix_business_matching_classification', table_name='businesses')
    op.create_index(op.f('ix_businesses_industry'), 'businesses', ['industry'], unique=False)
    op.create_index(op.f('ix_business_matching_industry'), 'businesses', ['status', 'industry'], unique=False)
    op.alter_column('businesses', 'industry',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('businesses', 'business_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('businesses', 'business_model')
    op.drop_column('businesses', 'sub_industry')
    # ### end Alembic commands ###
