"""update database schema

Revision ID: 923821662f81
Revises: abd5c33c9691
Create Date: 2026-09-17 11:05:53.266445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '923821662f81'
down_revision: Union[str, Sequence[str], None] = 'abd5c33c9691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_business_matching_industry', 'businesses', ['status', 'industry'], unique=False)
    op.create_index('ix_business_matching_location', 'businesses', ['status', 'state', 'city'], unique=False)
    op.create_index('ix_business_matching_price', 'businesses', ['status', 'asking_price'], unique=False)
    op.create_index('ix_buyer_preferences_target_industries_gin', 'buyer_preferences', ['target_industries'], unique=False, postgresql_using='gin')
    op.create_index('ix_buyer_preferences_target_locations_gin', 'buyer_preferences', ['target_locations'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_buyer_preferences_target_locations_gin', table_name='buyer_preferences', postgresql_using='gin')
    op.drop_index('ix_buyer_preferences_target_industries_gin', table_name='buyer_preferences', postgresql_using='gin')
    op.drop_index('ix_business_matching_price', table_name='businesses')
    op.drop_index('ix_business_matching_location', table_name='businesses')
    op.drop_index('ix_business_matching_industry', table_name='businesses')
    # ### end Alembic commands ###
