"""rename business name column

Revision ID: a9c13b634cb8
Revises: 0794d0599df8
Create Date: 2026-09-07 11:22:45.172878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c13b634cb8'
down_revision: Union[str, Sequence[str], None] = '0794d0599df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('idempotency_key', sa.String(length=255), nullable=False))
    op.create_unique_constraint('uq_business_seller_idempotency_key', 'businesses', ['seller_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_business_seller_idempotency_key', 'businesses', type_='unique')
    op.drop_column('businesses', 'idempotency_key')
    # ### end Alembic commands ###
