"""add processed events for consumer tracking

Revision ID: abd5c33c9691
Revises: 889b871a2fde
Create Date: 2026-09-13 07:42:22.496898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd5c33c9691'
down_revision: Union[str, Sequence[str], None] = '889b871a2fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('consumer', sa.String(length=50), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['outbox_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'consumer', name='uq_processed_event_consumer')
    )
    op.create_index(op.f('ix_processed_events_consumer'), 'processed_events', ['consumer'], unique=False)
    op.create_index(op.f('ix_processed_events_event_id'), 'processed_events', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_events_event_id'), table_name='processed_events')
    op.drop_index(op.f('ix_processed_events_consumer'), table_name='processed_events')
    op.drop_table('processed_events')
    # ### end Alembic commands ###
