"""create MatchBook tables

Revision ID: de0432131a38
Revises: 
Create Date: 2026-09-06 04:51:16.934142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de0432131a38'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_entity_id'), 'events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_events_entity_type'), 'events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_processed_at'), 'events', ['processed_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('verification_provider', sa.String(length=100), nullable=True),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_verification_status'), 'users', ['verification_status'], unique=False)
    op.create_table('buyer_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('buyer_type', sa.String(length=40), nullable=False),
    sa.Column('current_industry', sa.String(length=150), nullable=True),
    sa.Column('current_position', sa.String(length=150), nullable=True),
    sa.Column('business_experience_years', sa.Integer(), nullable=True),
    sa.Column('relevant_experience', sa.Text(), nullable=True),
    sa.Column('available_hours_per_week', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('available_hours_per_week IS NULL OR available_hours_per_week >= 0', name='ck_buyer_available_hours_nonnegative'),
    sa.CheckConstraint('business_experience_years IS NULL OR business_experience_years >= 0', name='ck_buyer_experience_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_profiles_user_id'), 'buyer_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_buyer_profiles_verification_status'), 'buyer_profiles', ['verification_status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.UUID(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('seller_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_profiles_user_id'), 'seller_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_seller_profiles_verification_status'), 'seller_profiles', ['verification_status'], unique=False)
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('dba', sa.String(length=255), nullable=True),
    sa.Column('business_type', sa.String(length=150), nullable=False),
    sa.Column('industry', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('years_in_operation', sa.Integer(), nullable=True),
    sa.Column('number_of_locations', sa.Integer(), nullable=True),
    sa.Column('number_of_routes', sa.Integer(), nullable=True),
    sa.Column('arr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('customer_concentration', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('asking_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('sde', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('owner_involvement_hours_per_week', sa.Integer(), nullable=True),
    sa.Column('transition_training_days', sa.Integer(), nullable=True),
    sa.Column('deal_preference', sa.String(length=20), nullable=True),
    sa.Column('preferred_sale_timeline', sa.String(length=50), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('arr IS NULL OR arr >= 0', name='ck_business_arr_nonnegative'),
    sa.CheckConstraint('asking_price IS NULL OR asking_price >= 0', name='ck_business_asking_price_nonnegative'),
    sa.CheckConstraint('customer_concentration IS NULL OR (customer_concentration >= 0 AND customer_concentration <= 100)', name='ck_business_customer_concentration_percentage'),
    sa.CheckConstraint('number_of_locations IS NULL OR number_of_locations >= 0', name='ck_business_locations_nonnegative'),
    sa.CheckConstraint('number_of_routes IS NULL OR number_of_routes >= 0', name='ck_business_routes_nonnegative'),
    sa.CheckConstraint('owner_involvement_hours_per_week IS NULL OR owner_involvement_hours_per_week >= 0', name='ck_business_owner_hours_nonnegative'),
    sa.CheckConstraint('sde IS NULL OR sde >= 0', name='ck_business_sde_nonnegative'),
    sa.CheckConstraint('transition_training_days IS NULL OR transition_training_days >= 0', name='ck_business_training_days_nonnegative'),
    sa.CheckConstraint('years_in_operation IS NULL OR years_in_operation >= 0', name='ck_business_years_nonnegative'),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_arr'), 'businesses', ['arr'], unique=False)
    op.create_index(op.f('ix_businesses_asking_price'), 'businesses', ['asking_price'], unique=False)
    op.create_index(op.f('ix_businesses_city'), 'businesses', ['city'], unique=False)
    op.create_index(op.f('ix_businesses_county'), 'businesses', ['county'], unique=False)
    op.create_index(op.f('ix_businesses_industry'), 'businesses', ['industry'], unique=False)
    op.create_index(op.f('ix_businesses_sde'), 'businesses', ['sde'], unique=False)
    op.create_index(op.f('ix_businesses_seller_id'), 'businesses', ['seller_id'], unique=False)
    op.create_index(op.f('ix_businesses_state'), 'businesses', ['state'], unique=False)
    op.create_index(op.f('ix_businesses_status'), 'businesses', ['status'], unique=False)
    op.create_index(op.f('ix_businesses_verification_status'), 'businesses', ['verification_status'], unique=False)
    op.create_table('buyer_financials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('funding_source', sa.String(length=40), nullable=True),
    sa.Column('reported_cash_available', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('verified_cash_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('financing_requested_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('financing_approved_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('lender_name', sa.String(length=255), nullable=True),
    sa.Column('lender_approval_status', sa.String(length=30), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('verification_provider', sa.String(length=100), nullable=True),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('provider_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('financing_approved_amount IS NULL OR financing_approved_amount >= 0', name='ck_buyer_financing_approved_nonnegative'),
    sa.CheckConstraint('financing_requested_amount IS NULL OR financing_requested_amount >= 0', name='ck_buyer_financing_requested_nonnegative'),
    sa.CheckConstraint('reported_cash_available IS NULL OR reported_cash_available >= 0', name='ck_buyer_cash_nonnegative'),
    sa.CheckConstraint('verified_cash_amount IS NULL OR verified_cash_amount >= 0', name='ck_buyer_verified_cash_nonnegative'),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_financials_buyer_id'), 'buyer_financials', ['buyer_id'], unique=True)
    op.create_index(op.f('ix_buyer_financials_lender_approval_status'), 'buyer_financials', ['lender_approval_status'], unique=False)
    op.create_index(op.f('ix_buyer_financials_verification_status'), 'buyer_financials', ['verification_status'], unique=False)
    op.create_table('buyer_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('target_industries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('maximum_purchase_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('minimum_required_sde', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('preferred_sde', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('minimum_required_arr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('preferred_arr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('preferred_owner_hours_per_week', sa.Integer(), nullable=True),
    sa.Column('required_transition_training_days', sa.Integer(), nullable=True),
    sa.Column('deal_preference', sa.String(length=20), nullable=True),
    sa.Column('real_estate_preference', sa.String(length=20), nullable=True),
    sa.Column('minimum_years_in_operation', sa.Integer(), nullable=True),
    sa.Column('accepts_customer_concentration_above_25_percent', sa.Boolean(), nullable=True),
    sa.Column('preferred_acquisition_timeline', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            minimum_required_arr IS NULL\n            OR preferred_arr IS NULL\n            OR minimum_required_arr <= preferred_arr\n            ', name='ck_buyer_arr_min_lte_preferred'),
    sa.CheckConstraint('\n            minimum_required_sde IS NULL\n            OR preferred_sde IS NULL\n            OR minimum_required_sde <= preferred_sde\n            ', name='ck_buyer_sde_min_lte_preferred'),
    sa.CheckConstraint('maximum_purchase_price IS NULL OR maximum_purchase_price >= 0', name='ck_buyer_max_price_nonnegative'),
    sa.CheckConstraint('minimum_required_arr IS NULL OR minimum_required_arr >= 0', name='ck_buyer_min_arr_nonnegative'),
    sa.CheckConstraint('minimum_required_sde IS NULL OR minimum_required_sde >= 0', name='ck_buyer_min_sde_nonnegative'),
    sa.CheckConstraint('preferred_arr IS NULL OR preferred_arr >= 0', name='ck_buyer_preferred_arr_nonnegative'),
    sa.CheckConstraint('preferred_owner_hours_per_week IS NULL OR preferred_owner_hours_per_week >= 0', name='ck_buyer_owner_hours_nonnegative'),
    sa.CheckConstraint('preferred_sde IS NULL OR preferred_sde >= 0', name='ck_buyer_preferred_sde_nonnegative'),
    sa.CheckConstraint('required_transition_training_days IS NULL OR required_transition_training_days >= 0', name='ck_buyer_training_days_nonnegative'),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_preferences_buyer_id'), 'buyer_preferences', ['buyer_id'], unique=True)
    op.create_table('business_financials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('verified_arr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('verified_sde', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('verified_ebitda', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('revenue_growth_percentage', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('verified_recurring_revenue_percentage', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('verified_customer_concentration', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('inventory_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('accounts_receivable', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('owner_add_backs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('financial_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('verification_provider', sa.String(length=100), nullable=True),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('provider_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('accounts_receivable IS NULL OR accounts_receivable >= 0', name='ck_business_financials_ar_nonnegative'),
    sa.CheckConstraint('inventory_value IS NULL OR inventory_value >= 0', name='ck_business_financials_inventory_nonnegative'),
    sa.CheckConstraint('verified_arr IS NULL OR verified_arr >= 0', name='ck_business_financials_arr_nonnegative'),
    sa.CheckConstraint('verified_customer_concentration IS NULL OR verified_customer_concentration BETWEEN 0 AND 100', name='ck_business_financials_customer_percentage'),
    sa.CheckConstraint('verified_ebitda IS NULL OR verified_ebitda >= 0', name='ck_business_financials_ebitda_nonnegative'),
    sa.CheckConstraint('verified_recurring_revenue_percentage IS NULL OR verified_recurring_revenue_percentage BETWEEN 0 AND 100', name='ck_business_financials_recurring_revenue_percentage'),
    sa.CheckConstraint('verified_sde IS NULL OR verified_sde >= 0', name='ck_business_financials_sde_nonnegative'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_financials_business_id'), 'business_financials', ['business_id'], unique=True)
    op.create_index(op.f('ix_business_financials_verification_status'), 'business_financials', ['verification_status'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('industry_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('geography_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('price_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('sde_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('arr_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('owner_involvement_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('customer_concentration_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('transition_training_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('deal_preference_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('industry_contribution', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('geography_contribution', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('arr_contribution', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('price_contribution', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('sde_contribution', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('owner_involvement_contribution', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('customer_concentration_contribution', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('transition_training_contribution', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('deal_preference_contribution', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('matching_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('arr_score IS NULL OR arr_score BETWEEN 0 AND 1', name='ck_match_arr_score_range'),
    sa.CheckConstraint('customer_concentration_score IS NULL OR customer_concentration_score BETWEEN 0 AND 1', name='ck_match_customer_concentration_score_range'),
    sa.CheckConstraint('deal_preference_score IS NULL OR deal_preference_score BETWEEN 0 AND 1', name='ck_match_deal_score_range'),
    sa.CheckConstraint('geography_score IS NULL OR geography_score BETWEEN 0 AND 1', name='ck_match_geography_score_range'),
    sa.CheckConstraint('industry_score IS NULL OR industry_score BETWEEN 0 AND 1', name='ck_match_industry_score_range'),
    sa.CheckConstraint('owner_involvement_score IS NULL OR owner_involvement_score BETWEEN 0 AND 1', name='ck_match_owner_score_range'),
    sa.CheckConstraint('price_score IS NULL OR price_score BETWEEN 0 AND 1', name='ck_match_price_score_range'),
    sa.CheckConstraint('score BETWEEN 0 AND 1', name='ck_match_score_range'),
    sa.CheckConstraint('sde_score IS NULL OR sde_score BETWEEN 0 AND 1', name='ck_match_sde_score_range'),
    sa.CheckConstraint('transition_training_score IS NULL OR transition_training_score BETWEEN 0 AND 1', name='ck_match_training_score_range'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_id', 'business_id', name='uq_buyer_business_match')
    )
    op.create_index(op.f('ix_matches_business_id'), 'matches', ['business_id'], unique=False)
    op.create_index('ix_matches_business_status', 'matches', ['business_id', 'status'], unique=False)
    op.create_index(op.f('ix_matches_buyer_id'), 'matches', ['buyer_id'], unique=False)
    op.create_index('ix_matches_buyer_status', 'matches', ['buyer_id', 'status'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_match_id'), 'conversations', ['match_id'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_financials_id', sa.UUID(), nullable=True),
    sa.Column('business_financials_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('storage_provider', sa.String(length=30), nullable=False),
    sa.Column('bucket_name', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('verification_provider', sa.String(length=100), nullable=True),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            (\n                buyer_financials_id IS NOT NULL\n                AND business_financials_id IS NULL\n            )\n            OR\n            (\n                buyer_financials_id IS NULL\n                AND business_financials_id IS NOT NULL\n            )\n            ', name='ck_document_exactly_one_owner'),
    sa.CheckConstraint('file_size IS NULL OR file_size >= 0', name='ck_document_file_size_nonnegative'),
    sa.ForeignKeyConstraint(['business_financials_id'], ['business_financials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['buyer_financials_id'], ['buyer_financials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket_name', 'object_key', name='uq_document_r2_object')
    )
    op.create_index(op.f('ix_documents_business_financials_id'), 'documents', ['business_financials_id'], unique=False)
    op.create_index(op.f('ix_documents_buyer_financials_id'), 'documents', ['buyer_financials_id'], unique=False)
    op.create_index(op.f('ix_documents_verification_status'), 'documents', ['verification_status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('ndas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('buyer_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seller_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ndas_document_id'), 'ndas', ['document_id'], unique=True)
    op.create_index(op.f('ix_ndas_match_id'), 'ndas', ['match_id'], unique=True)
    op.create_index(op.f('ix_ndas_status'), 'ndas', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ndas_status'), table_name='ndas')
    op.drop_index(op.f('ix_ndas_match_id'), table_name='ndas')
    op.drop_index(op.f('ix_ndas_document_id'), table_name='ndas')
    op.drop_table('ndas')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_documents_verification_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_buyer_financials_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_business_financials_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_conversations_match_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index('ix_matches_buyer_status', table_name='matches')
    op.drop_index(op.f('ix_matches_buyer_id'), table_name='matches')
    op.drop_index('ix_matches_business_status', table_name='matches')
    op.drop_index(op.f('ix_matches_business_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_business_financials_verification_status'), table_name='business_financials')
    op.drop_index(op.f('ix_business_financials_business_id'), table_name='business_financials')
    op.drop_table('business_financials')
    op.drop_index(op.f('ix_buyer_preferences_buyer_id'), table_name='buyer_preferences')
    op.drop_table('buyer_preferences')
    op.drop_index(op.f('ix_buyer_financials_verification_status'), table_name='buyer_financials')
    op.drop_index(op.f('ix_buyer_financials_lender_approval_status'), table_name='buyer_financials')
    op.drop_index(op.f('ix_buyer_financials_buyer_id'), table_name='buyer_financials')
    op.drop_table('buyer_financials')
    op.drop_index(op.f('ix_businesses_verification_status'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_status'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_state'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_seller_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_sde'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_industry'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_county'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_city'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_asking_price'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_arr'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_seller_profiles_verification_status'), table_name='seller_profiles')
    op.drop_index(op.f('ix_seller_profiles_user_id'), table_name='seller_profiles')
    op.drop_table('seller_profiles')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_buyer_profiles_verification_status'), table_name='buyer_profiles')
    op.drop_index(op.f('ix_buyer_profiles_user_id'), table_name='buyer_profiles')
    op.drop_table('buyer_profiles')
    op.drop_index(op.f('ix_users_verification_status'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_events_processed_at'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_entity_type'), table_name='events')
    op.drop_index(op.f('ix_events_entity_id'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
